# Generated by Django 5.2.5 on 2025-09-25 19:09

import train.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traintype",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=train.models.train_type_image_file_path
            ),
        ),
    ]
