# Generated by Django 5.2.5 on 2025-09-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train", "0002_alter_traintype_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="number_train",
            field=models.PositiveIntegerField(),
        ),
    ]
